Jlc/add course run view set wrapper
eduNEXT/eox-nelp pull request #103
Opened 2023-10-26 20:19 UTC by johanv26

## Description

Eox-nelp version for CourseRunViewSet in CMS
 feat: wrapper cms CourseRunViewSet view
The eox-nelp version endpoint CourseRunViewSet  is the same as CMS.

`{studio_url}/eox-nelp/api/v1/course_runs/` is the same of  `{studio_url}/api/v1/course_runs/`
### Before
Only eox-info endpoint in cms eox-nelp urls.
### After

![Peek 2023-10-26 15-14](https://github.com/eduNEXT/eox-nelp/assets/51926076/d5e4b9ca-dcf3-4425-bb8f-ba8f19f01841)

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

2023-10-27 17:01 UTC, andrey-canon requested changes

2023-10-27 21:16 UTC, johanv26 commented on eox_nelp/settings/common.py
> +    settings.EOX_NELP_CMS_API_VIEWS = 'eox_nelp.edxapp_wrapper.backends.cms_api_views_m_v1'
YOu are right I passed it.

2023-10-27 21:31 UTC, johanv26 commented on eox_nelp/edxapp_wrapper/test_backends/__init__.py
> +from rest_framework.viewsets import GenericViewSet
SOlved in 2614e14608d26c435592796e0bda302f9ba50511

2023-10-27 21:31 UTC, johanv26 commented on eox_nelp/settings/common.py
> +    settings.EOX_NELP_CMS_API_VIEWS = 'eox_nelp.edxapp_wrapper.backends.cms_api_views_m_v1'
5eb37be84590afdef704353c92d7d27af42c2273

2023-10-27 21:31 UTC, johanv26 commented on eox_nelp/edxapp_wrapper/test_backends/cms_api_views_m_v1.py
> +COURSE_RUN_TEST_RESPONSE = {
a2d3a16

2023-10-27 21:31 UTC, johanv26 commented on eox_nelp/edxapp_wrapper/backends/cms_api_views_m_v1.py
9592908

2023-10-27 21:41 UTC, johanv26 commented on eox_nelp/cms/api/v1/views.py
> +class NelpCourseRunViewSet(CourseRunViewSet):
[43230d0](https://github.com/eduNEXT/eox-nelp/pull/103/commits/43230d0f3f78bb50d5cbfc68d8d8958b42489563)

2023-10-27 21:43 UTC, johanv26 commented on eox_nelp/edxapp_wrapper/test_backends/cms_api_views_m_v1.py
> +    def list(self, request, *args, **kwargs):  # lint-amnesty, pylint: disable=unused-argument
I dont know it, I bring it from here.
https://github.com/eduNEXT/edunext-platform/blob/ednx-release/mango.master.nelp/cms/djangoapps/api/v1/views/course_runs.py#L46
Is something like from Edx Lint.
So in this case I could removed.
[43230d0](https://github.com/eduNEXT/eox-nelp/pull/103/commits/43230d0f3f78bb50d5cbfc68d8d8958b42489563)

2023-10-30 19:16 UTC, andrey-canon approved these changes

2023-10-30 19:16 UTC, andrey-canon commented on eox_nelp/edxapp_wrapper/cms_api.py
> +    backend: Imported CMS api module by using the plugin settings.
```suggestion
    cms_api: Imported CMS api module by using the plugin settings.
```

2023-10-30 19:16 UTC, andrey-canon commented on eox_nelp/edxapp_wrapper/cms_api.py
> +This contains  the required api view from cms/api/../views
This could contain all the api content not just views

2023-10-30 19:37 UTC, merged