Jlc/phone validation backend
eduNEXT/eox-nelp pull request #144
Opened 2024-03-22 19:32 UTC by johanseto

## Description

Add basic backend with generate and validate endpoint for OTP in phone validation.

Useful information to include:
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.

## Testing instructions

Checkout this branch in eox-nelp.

Checkout the nelp-edx-theme in to this branch. 
https://github.com/nelc/nelp-edx-theme/pull/174
Add the following settings:
``` python
MFE_CONFIG["PHONE_VALIDATION_API_URL"] = "/eox-nelp/api/phone-validation/v1"
```
1. Login with an account without phone_number in profile in admin.
![image](https://github.com/eduNEXT/eox-nelp/assets/51926076/6105d64b-97d3-4f57-bd57-bf8fb84a9c18)
2. Go to `/dashboard` and check the modal of phone confirmation is working.
![image](https://github.com/eduNEXT/eox-nelp/assets/51926076/2b485f85-ef4e-4019-9462-83295e362119)
3. Enter a test phone -number and check there is a log related in lms related the creation of the otp.
![Peek 2024-03-22 14-24](https://github.com/eduNEXT/eox-nelp/assets/51926076/a2bdfb55-c2c4-4604-8214-f2394b69e349)

5. Then you need the validation code, to get it you can go to cache and find it using `{username}-{phone_number}`. 
![image](https://github.com/eduNEXT/eox-nelp/assets/51926076/2809826f-2954-4672-9760-8ed3d4d8c1be)
6. Add the code in the modal of phone_validation to continue the flow, check there is a log of validating, and the modal return with success.
![Peek 2024-03-22 14-28](https://github.com/eduNEXT/eox-nelp/assets/51926076/06c20694-1b15-4024-98a4-72e437fb26b4)

7. Reload `/dashboard`, verify that  phone_validation modal doesn't appear. Also in the admin profile phone_number has been updated.

![Peek 2024-03-22 14-29](https://github.com/eduNEXT/eox-nelp/assets/51926076/c28929b8-fef9-458f-9c53-d09aeba13aab)

## Additional information

Jira story:
https://edunext.atlassian.net/browse/FUTUREX-692

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

2024-04-01 16:05 UTC, andrey-canon requested changes

2024-04-03 22:34 UTC, johanseto commented on eox_nelp/tests/test_utils.py
> +def get_key_expiration(key):
9d6711b3b0f8dadabd9674d54775b3aeeb746003

2024-04-03 22:34 UTC, johanseto commented on eox_nelp/tests/test_utils.py
> +    """Util to get the expiration time of a key cache in seconds."""
https://github.com/eduNEXT/eox-nelp/pull/144/commits/9d6711b3b0f8dadabd9674d54775b3aeeb746003

2024-04-03 22:36 UTC, johanseto commented on eox_nelp/tests/test_utils.py
647eb5ae0889f41b159def43753126493af3eb91

2024-04-04 16:01 UTC, andrey-canon requested changes

2024-04-04 17:54 UTC, andrey-canon commented on eox_nelp/tests/utils.py
> +        key <str>: bla blabla
:)

2024-04-04 17:54 UTC, andrey-canon approved these changes

2024-04-04 20:25 UTC, merged