feat: add engines model
eduNEXT/eox-nelp pull request #219
Opened 2024-09-30 23:47 UTC by johanseto

feat: add test utils

feat: add tests

## Description

Describe what this pull request changes, and why. Include implications for people using this change.

Useful information to include:
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.

## Testing instructions

### Before

### After

## Additional information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, security, or accessibility.
- Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

2024-10-02 18:01 UTC, andrey-canon requested changes

2024-10-23 00:10 UTC, johanseto commented
@andrey-canon I unify the courses section for RTI and EAD.
![image](https://github.com/user-attachments/assets/4f0f4c17-0e15-49a9-bec4-2f84aee7ffee)

2024-10-25 17:28 UTC, andrey-canon approved these changes

2024-10-25 17:28 UTC, andrey-canon commented on eox_nelp/pearson_vue/utils.py
> +    """_summary_
summary ?

2024-10-28 23:28 UTC, merged